spring.application.name=contactos
spring.datasource.url=jdbc:mysql://localhost:3306/contactos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Anotacion para crear la base de datos automaticamente
spring.jpa.hibernate.ddl-auto=update
# Anotacion para mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
# Modificar el puerto si es necesario.
# server.port=8080




