spring.application.name=inventarios
# Conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Spring Boot actualizará automáticamente la estructura de la base de datos según las entidades (@Entity).
spring.jpa.hibernate.ddl-auto=update
# Permitir que se muestren las consultas SQL en la consola
spring.jpa.show-sql=true
# Configurar el patron de logging para que se muestren las consultas SQL en la consola
# (Tambien se puede configurar en el archivo logback-spring.xml)
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
# Configurar el nivel de logging (INFO, DEBUG, WARN, ERROR)
logging.level.org=INFO
# Opcional, configurar niveles de logging para paquetes específicos
#logging.level.fm.inventarios=DEBUG
#logging.level.org.springframework=WARN
# Configurar el puerto del servidor (opcional, por defecto es 8080)
#server.port=8081
# No mostrar el banner cada vez que se ejecute el proyecto
spring.main.banner-mode=off