spring.application.name=zona_fit
#conexion mysql
spring.datasource.url=jdbc:mysql://localhost:3306/zona_fit_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Evitar crear el esquema de base de datos.
spring.jpa.hibernate.ddl-auto=none
# Mostrar el detalle de cada sentencia que se ejecuta en la base de datos.
spring.jpa.show-sql=false
# Desactivar tomcat
spring.main.web-application-type=none

